### ISSUE TITLE
Configuration file is wanted

### ISSUE THREAD

**Issue by gvlipunova** [hombit/freddi#13]
Sometimes, non-defaults values of the arguments are better to be stored in the configuration file. Make Freddi take arguments from a file.

**Comment by hombit** [comment]
[Boost docs](http://www.boost.org/doc/libs/1_62_0/doc/html/program_options/overview.html#idm45927870538032) can help

**Comment by hombit** [comment]
Initial support is in b60dfe4

**Comment by hombit** [comment]
Done in e8af2ca
