### ISSUE TITLE
Regarding the difference in Sigma distribution in C++ and python version 2.

### ISSUE THREAD

**Issue by AnkitHMishra** [hombit/freddi#66]
Dear Prof. Malanchev,
I was trying to verify the Sigma distribution of for all 35 days of the outburst of 4U 1543 − 47,  following your paper. I added a print command to print Sigma  in the "freddi.state.cpp".  While running providing the below parametrs in terminal version as well as the python version to print Sigma :
./freddi --Mx=9.4 --period=1.116 --Mopt=2.5 --alpha=0.23 --colourfactor=1.7 --inclination=20.7 --time=35 --tau=1 --distance=9.1 --Mdisk0=2.70002635e+25 --Cirr=1.5e-4 --kerr=0.4 --rout=0.7 --opacity=Kramers --initialcond=powerF --powerorder=1.4

I found the that SigmaOut from the c++ code in 'freddi.dat', matches quite closely with the last element of result.Sigma array in freddi at each time step, but the whole distribution (from initial  to final h  )for each time  step does not match.  I have attached the Python version Sigma printout snip and C++ print statement which I added in freddi.state.  
  
![Sigma_Python](https://github.com/hombit/freddi/assets/107344513/da248adc-5fd6-41a8-9f5c-af93b7dc8df4)
![C++ Sigma print code](https://github.com/hombit/freddi/assets/107344513/3a677207-aa44-4211-a896-884826f36286)

**Comment by hombit** [comment]
I'm closing it, but feel free to reopen if have more questions on this
